name: matthewjmoran.com

services:
  web:
    build:
      context: .
      target: development
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: ./web
          target: /usr/local/app
          action: sync
          ignore:
            - node_modules/
        - path: package.json
          action: rebuild
