name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - 'trunk'
    paths:
      - 'web/**'
      - '.github/workflows/**'

jobs:
  build:
    name: 'Build Ubuntu'

    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Fetch Tags
        run: git fetch --tags

      - name: Retrieve Tag
        id: tag
        run: |
          tag=$(git tag --points-at ${{ github.sha }})
          if [ -z "$tag" ]; then
            echo "No tag for this commit" # Output to console if no tag is found
          else
            echo "Tag for this commit: ${tag}" # Output to console if tag is found
          fi
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: 'web/pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        env:
          BASE_PATH: ''
        run: pnpm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: 'web/build/'

  preview:
    name: 'Deploy / Preview'

    needs: build
    runs-on: ubuntu-latest

    environment:
      name: cloudflare-pages
      url: https://preview.matthewjmoran.pages.dev/

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: 'build/'

      - name: Deploy to Preview
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: >
            pages deploy build --project-name=${{ vars.CLOUDFLARE_PROJECT }}
            --branch=preview

  production:
    name: 'Deploy / Production'

    needs: build
    if: ${{ startsWith(needs.build.outputs.tag, 'v') }}
    runs-on: ubuntu-latest

    environment:
      name: cloudflare-pages
      url: https://matthewjmoran.com/

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: 'build/'

      - name: Deploy to Production
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: >
            pages deploy build --project-name=${{ vars.CLOUDFLARE_PROJECT }}
            --branch=production