name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/deploy.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: 'web/pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        env:
          BASE_PATH: ''
        run: |
          pnpm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: 'web/build/'

  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: cloudflare-pages
      url: https://matthewjmoran.com

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: 'build/' 

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUND_ID }}
          command: pages deploy build --project-name=${{ vars.CLOUDFLARE_PROJECT }}